Later(function()
	require("mini.ai").setup({ n_lines = 500 })
	--TODO CTRL-G for toggle comment in insertmode

	require("dij.plugins.mini.comment")
	require("dij.plugins.mini.keymap")
	require("dij.plugins.mini.move")
	--CONFLICT keymap
	-- require("mini.operators").setup()
	-- require("mini.pairs").setup()
	require("mini.splitjoin").setup()
	require("mini.surround").setup()
	require("mini.bracketed").setup()
	require("dij.plugins.mini.clue")
	require("mini.jump").setup()
	require("mini.misc").setup({ make_global = { "put", "put_text", "zoom" } })
	require("mini.visits").setup()
	-- require("mini.cursorword").setup()
	require("dij.plugins.mini.hipatterns")
	require("mini.icons").setup()
	-- require("mini.notify").setup({ lsp_progress = { enable = false } })
	require("dij.plugins.mini.statusline")
	require("mini.trailspace").setup()
end)
